# Google App Engine configuration
runtime: python311
env: standard

# Instance class (F1 = free/shared, F2 = more memory)
instance_class: F1

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

# Environment variables
env_variables:
  PORT: "8080"
  PYTHONPATH: "/app"

# Handlers
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

# Network settings
network:
  session_affinity: true

# Enable WebSocket
inbound_services:
- warmup

entrypoint: python web_api.py