# Cloud Build configuration for automated deployment
steps:
  # Install dependencies
  - name: 'python:3.11'
    entrypoint: pip
    args: ['install', '-r', 'requirements_web.txt', '--user']

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']

  # Deploy to Cloud Run (alternative)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'botphia-dashboard'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8888'

timeout: '1200s'