app = "botphia-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.professional"

[env]
  PORT = "8000"
  SIGNAL_SCAN_INTERVAL = "60"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [services.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 100

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = 512
  cpus = 1

[mounts]
  source = "data"
  destination = "/app/data"