# fly.toml para BotPhia Lightweight
app = "botphia-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.lightweight"

[env]
  PORT = "8000"
  TRADING_MODE = "demo"
  SIGNAL_SCAN_INTERVAL = "60"
  DATABASE_PATH = "/app/data/trading_bot.db"
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "60s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false

[mounts]
  source = "data"
  destination = "/app/data"