# fly.toml for BotPhia Hybrid Trading System
app = "botphia-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.hybrid"

[env]
  PORT = "8000"
  TRADING_MODE = "demo"
  SIGNAL_SCAN_INTERVAL = "30"
  AUTO_TRADE = "false"
  DATABASE_PATH = "/app/data/trading_bot.db"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "30s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "5s"
    tls_skip_verify = false

[mounts]
  source = "data"
  destination = "/app/data"